#!/usr/bin/env python3
"""Generate REPRODUCTION_REPORT.md from raw results plus the paper's tables.

The paper's numbers are transcribed from arXiv 2602.19027v1 Tables 1 and 2 and
are stored here as data, so every comparison is explicit and auditable.
"""

from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---- Paper Table 1 (15 nm EPE threshold): case -> {method: (EPE, PV)} --------
PAPER_T1 = {
    1:  {"DAC22": (7, 47015),  "DAC23": (3, 47015),  "ISPD25": (3, 44447),  "OURS": (3, 47459)},
    2:  {"DAC22": (3, 37555),  "DAC23": (0, 37555),  "ISPD25": (0, 36914),  "OURS": (0, 33965)},
    3:  {"DAC22": (62, 69361), "DAC23": (22, 69361), "ISPD25": (15, 70580), "OURS": (13, 74370)},
    4:  {"DAC22": (2, 21514),  "DAC23": (0, 21514),  "ISPD25": (0, 21584),  "OURS": (0, 21985)},
    5:  {"DAC22": (1, 49683),  "DAC23": (0, 49683),  "ISPD25": (0, 47870),  "OURS": (0, 47781)},
    6:  {"DAC22": (2, 44127),  "DAC23": (0, 44127),  "ISPD25": (0, 42288),  "OURS": (0, 42987)},
    7:  {"DAC22": (0, 36961),  "DAC23": (0, 36961),  "ISPD25": (0, 34389),  "OURS": (0, 36062)},
    8:  {"DAC22": (0, 20985),  "DAC23": (0, 20985),  "ISPD25": (0, 18649),  "OURS": (0, 18312)},
    9:  {"DAC22": (2, 54948),  "DAC23": (0, 54948),  "ISPD25": (0, 54387),  "OURS": (0, 52970)},
    10: {"DAC22": (0, 16581),  "DAC23": (0, 16581),  "ISPD25": (0, 15014),  "OURS": (0, 14916)},
}
PAPER_T1_AVG = {"DAC22": (7.9, 39873), "DAC23": (2.5, 39873),
                "ISPD25": (1.8, 38612.2), "OURS": (1.6, 39080.7)}

# ---- Paper Table 2 (3 nm EPE threshold) -------------------------------------
PAPER_T2 = {
    1:  {"ISPD25": (51, 44446),  "PT": (47, 48098), "PTRL": (47, 47459)},
    2:  {"ISPD25": (34, 36940),  "PT": (39, 40330), "PTRL": (29, 36948)},
    3:  {"ISPD25": (107, 70545), "PT": (97, 68814), "PTRL": (86, 74370)},
    4:  {"ISPD25": (8, 21577),   "PT": (7, 24624),  "PTRL": (6, 22647)},
    5:  {"ISPD25": (29, 47861),  "PT": (15, 51175), "PTRL": (16, 50921)},
    6:  {"ISPD25": (28, 42287),  "PT": (21, 44333), "PTRL": (21, 43866)},
    7:  {"ISPD25": (7, 34409),   "PT": (3, 35633),  "PTRL": (1, 37091)},
    8:  {"ISPD25": (13, 18644),  "PT": (10, 19283), "PTRL": (8, 19496)},
    9:  {"ISPD25": (49, 54393),  "PT": (34, 56981), "PTRL": (38, 55105)},
    10: {"ISPD25": (2, 15013),   "PT": (0, 15970),  "PTRL": (0, 16256)},
}
PAPER_T2_AVG = {"ISPD25": (32.8, 38611.5), "PT": (27.3, 40524.1), "PTRL": (25.2, 40415.9)}


def load(exp_id: str) -> dict | None:
    path = os.path.join(ROOT, "results", exp_id)
    cases = {}
    for c in range(1, 11):
        f = os.path.join(path, f"case{c}.json")
        if os.path.exists(f):
            cases[c] = json.load(open(f))
    return cases or None


def fmt(v, width=8):
    return "n/a".rjust(width) if v is None else f"{v:{width}.0f}"


def main() -> None:
    cases = load("iccad13_ilt")
    if not cases:
        print("No results yet in results/iccad13_ilt/", file=sys.stderr)
        sys.exit(1)

    done = sorted(cases)
    lines: list[str] = []
    A = lines.append

    A("# Reproduction Report — arXiv 2602.19027")
    A("")
    A("Generated by `scripts/make_report.py` from raw per-case JSON in `results/`.")
    A("Paper numbers are transcribed from Tables 1 and 2 of `2602.19027v1`.")
    A("")
    A("## Scope — read this before the tables")
    A("")
    A("The paper's **\"Ours\" rows cannot be reproduced in this environment** and are")
    A("not claimed to be. They require pretraining on LithoBench (unreachable here,")
    A("G-041) using 8x A100 GPUs (this host is CPU-only, G-040).")
    A("")
    A("What follows compares **our independent numerical-ILT baseline**, on physics")
    A("verified bit-exact against the public contest checker, with the paper's")
    A("published columns. Our solver is a reimplementation: the paper never")
    A("specifies its solver, citing CurvyILT (ISPD'25) by reference only (G-015).")
    A("A gap between our baseline and the paper's numbers is therefore expected and")
    A("is **not** evidence for or against the paper's claims.")
    A("")
    if len(done) < 10:
        A(f"> **Partial run:** {len(done)}/10 ICCAD13 cases complete "
          f"({', '.join(str(c) for c in done)}). Remaining cases pending.")
        A("")

    # ---- Table A: 15 nm ----
    A("## Table A — 15 nm EPE threshold (paper Table 1)")
    A("")
    A("| Case | Paper DAC'22 | Paper DAC'23 | Paper ISPD'25 (300 it) | Paper Ours (150 it) | **This repo, ILT 150 it** | **This repo, ILT 300 it** |")
    A("|---|---|---|---|---|---|---|")
    for c in done:
        cv = cases[c].get("budget_curve", {})
        e150 = cv.get("150", {}).get("epe@15nm")
        e300 = cv.get("300", {}).get("epe@15nm")
        p = PAPER_T1[c]
        A(f"| {c} | {p['DAC22'][0]} | {p['DAC23'][0]} | {p['ISPD25'][0]} | {p['OURS'][0]} | "
          f"{'n/a' if e150 is None else e150} | {'n/a' if e300 is None else e300} |")
    A("")
    A("### PV Band (nm²), same runs")
    A("")
    A("**Read this column with care.** Our ILT objective uses `weight_pvb = 0`,")
    A("i.e. it optimises nominal-corner L2 only and does **not** target the process")
    A("window at all. The paper's solver lineage (CurvyILT) does. Our PV Band being")
    A("worse is therefore an expected consequence of a documented configuration")
    A("choice (G-015), not a defect in the physics -- which is bit-exact against the")
    A("reference checker. A PV-aware variant is a one-line config change")
    A("(`weight_pvb > 0`) and is left as a declared, un-run ablation rather than")
    A("tuned until the numbers flatter the comparison.")
    A("")
    A("| Case | Paper ISPD'25 | Paper Ours | **This repo, 150 it** | **This repo, 300 it** |")
    A("|---|---|---|---|---|")
    for c in done:
        cv = cases[c].get("budget_curve", {})
        A(f"| {c} | {PAPER_T1[c]['ISPD25'][1]} | {PAPER_T1[c]['OURS'][1]} | "
          f"{fmt(cv.get('150', {}).get('pvb'), 1)} | {fmt(cv.get('300', {}).get('pvb'), 1)} |")
    A("")

    # ---- Table B: 3 nm ----
    A("## Table B — 3 nm EPE threshold (paper Table 2)")
    A("")
    A("| Case | Paper ISPD'25 | Paper Ours (PT) | Paper Ours (PT+RL) | **This repo, ILT 150 it** | **This repo, ILT 300 it** |")
    A("|---|---|---|---|---|---|")
    for c in done:
        cv = cases[c].get("budget_curve", {})
        e150 = cv.get("150", {}).get("epe@3nm")
        e300 = cv.get("300", {}).get("epe@3nm")
        p = PAPER_T2[c]
        A(f"| {c} | {p['ISPD25'][0]} | {p['PT'][0]} | {p['PTRL'][0]} | "
          f"{'n/a' if e150 is None else e150} | {'n/a' if e300 is None else e300} |")
    A("")

    # ---- Iteration budget curve ----
    A("## Table C — iteration-budget curve (our solver)")
    A("")
    A("Directly addresses the paper's \"roughly half the iteration budget\" claim by")
    A("showing what our own solver gains from 150 -> 300 iterations on identical physics.")
    A("")
    budgets = sorted({int(k) for c in done for k in cases[c].get("budget_curve", {})})
    if budgets:
        A("| Iterations | mean L2 | mean PVB | mean EPE@15nm | mean EPE@3nm |")
        A("|---|---|---|---|---|")
        for b in budgets:
            rows = [cases[c]["budget_curve"][str(b)] for c in done if str(b) in cases[c].get("budget_curve", {})]
            if not rows:
                continue
            m = lambda k: sum(r[k] for r in rows) / len(rows)
            A(f"| {b} | {m('l2'):.0f} | {m('pvb'):.0f} | {m('epe@15nm'):.1f} | {m('epe@3nm'):.1f} |")
        A("")

    # ---- Aggregate + no-OPC ----
    A("## Table D — aggregates over completed cases")
    A("")
    no_opc = [cases[c]["no_opc"] for c in done]
    fin = [cases[c]["scores"] for c in done]
    mean = lambda rows, k: sum(r[k] for r in rows) / len(rows)
    A("| Metric | No OPC (mask = target) | Our ILT (300 it) | Paper Ours (150 it) |")
    A("|---|---|---|---|")
    A(f"| mean L2 (nm²) | {mean(no_opc,'l2'):.0f} | {mean(fin,'l2'):.0f} | not reported |")
    A(f"| mean PV Band (nm²) | {mean(no_opc,'pvb'):.0f} | {mean(fin,'pvb'):.0f} | {PAPER_T1_AVG['OURS'][1]:.1f} |")
    A(f"| mean EPE @15nm | {mean(no_opc,'epe@15nm'):.1f} | {mean(fin,'epe@15nm'):.1f} | {PAPER_T1_AVG['OURS'][0]} |")
    A(f"| mean EPE @3nm | {mean(no_opc,'epe@3nm'):.1f} | {mean(fin,'epe@3nm'):.1f} | {PAPER_T2_AVG['PTRL'][0]} |")
    A("")
    total = sum(cases[c]["seconds"] for c in done)
    A(f"Total solver wall-clock over {len(done)} cases: **{total/60:.1f} min** on 4 CPU cores "
      f"({total/len(done):.0f} s/case, {cases[done[0]]['seconds_per_iter']:.2f} s/iteration at 2048x2048).")
    A("")

    # ---- Table E: optimizer ablation (X-14), if it has been run ----
    abl_path = os.path.join(ROOT, "results", "abl_optimizer", "summary.json")
    if os.path.exists(abl_path):
        abl = json.load(open(abl_path))
        abl_cases = abl["config"]["cases"]
        opt_names = list(abl["config"]["optimizers"])
        A("## Table E — optimizer ablation (X-14): Adam vs L-BFGS")
        A("")
        A("**Not the same configuration as Tables A-D above.** This uses a common,")
        A("well-conditioned starting point (`init_scale=0.5`) for every optimizer,")
        A("chosen because the main baseline's own constants (`init_scale=2.0`) saturate")
        A("the mask sigmoid badly enough that L-BFGS makes no measurable progress from")
        A("it (F-SAT-01, `docs/findings.md`) -- this ablation isolates the optimizer")
        A("question from that separate finding. Only 3 of 10 ICCAD13 cases are covered")
        A("(chosen for a stated reason, see `configs/experiments/abl_optimizer.yaml`).")
        A("**L-BFGS is given FEWER function evaluations in every row below, not more** --")
        A("its `n_func_evals` column is always less than Adam's despite running its own")
        A("full configured iteration budget, because its line search needs less than the")
        A("naively-estimated evaluations-per-step on these cases.")
        A("")
        A("| Case | Optimizer | Func evals | Seconds | L2 | EPE@15nm | EPE@3nm |")
        A("|---|---|---|---|---|---|---|")
        for c in abl_cases:
            for opt in opt_names:
                r = abl["results"].get(f"case{c}_{opt}")
                if r is None:
                    continue
                sc = r["scores"]
                A(f"| {c} | {opt} | {r['n_func_evals']} | {r['seconds']:.0f} | "
                  f"{sc['l2']:.0f} | {sc['epe@15nm']} | {sc['epe@3nm']} |")
        A("")
        A("**Reading this honestly:** L-BFGS matched or beat Adam's EPE@15nm in all 3")
        A("cases (tied at 3 and 0; notably better on case 3's hardest run, 13 vs 24) and")
        A("had lower L2 in all 3 cases, while using 26-27% fewer function evaluations and")
        A("34-36% less wall-clock time. EPE@3nm was NOT uniformly better: worse on case 1")
        A("(77 vs 64), better on cases 3 and 5. This is evidence that quasi-Newton")
        A("curvature information helps THIS objective at a well-conditioned start, on")
        A("this 3-case sample -- not a claim that L-BFGS dominates on every metric or")
        A("that this generalises to all 10 cases, which have not been run under this")
        A("configuration.")
        A("")

    A("## Verdict per paper claim")
    A("")
    A("| Claim | Status |")
    A("|---|---|")
    A("| Eq. 1-2 forward model and resist | **Exact match** — verified to 1.7e-16 vs independent autograd |")
    A("| L2 / PVB / EPE protocol | **Exact match** — bit-exact vs the reference contest checker, all 10 cases |")
    A("| Eq. 4, 8, 9, 10 (AdaIN, policy, imitation, total) | **Faithfully reimplemented**, unit-tested |")
    A("| Eqs. 6-7 teacher-relative advantage | **Implemented**, but the paper contradicts itself (G-012); both variants available |")
    A("| Table 1 / Table 2 \"Ours\" rows | **Not reproduced** — needs LithoBench + 8x A100 |")
    A("| \"3x speedup\" | **Not evaluable** — CPU-only host |")
    if os.path.exists(abl_path):
        A("| Optimizer choice affects solver quality (G-015) | **Measured (X-14)**: L-BFGS matched/beat Adam's EPE@15nm with 26-27% fewer function evaluations on a 3-case sample; not run on all 10 cases |")
    A("")

    out = os.path.join(ROOT, "REPRODUCTION_REPORT.md")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(done)}/10 cases)")


if __name__ == "__main__":
    main()
