"""
Array Generator Module

This module provides tools for generating synthetic periodic arrays of target
features (contacts, vias) for testing and validation of SRAF consistency
checking algorithms.

Core Components:
- Polygon: Immutable polygon representation in canonical form
- UnitCell: Unit cell definition for periodic arrays
- Array: Periodic array generated by tiling a unit cell

Constructors:
- rectangle_centered: Create rectangle from center point
- rectangle_corner: Create rectangle from corner point

Templates:
- simple_contact_array: Simple square contact array (1 per cell)
- staggered_contact_array: Brick/staggered array (2 per cell)
- cluster_contact_array: Cluster array (N per cell)

Export Functions:
- export_polygon_vertices: Export vertices to text file
- export_polygon_centroids: Export centroids to text file
- export_to_gds: Export array to GDS format
- export_array_metadata: Export array metadata

Visualization Functions:
- plot_unit_cell: Plot unit cell
- plot_array: Plot array
- save_unit_cell_plot: Save unit cell plot to file
- save_array_plot: Save array plot to file
"""

from array_generator.core import Polygon, UnitCell, Array
from array_generator.constructors import rectangle_centered, rectangle_corner
from array_generator.templates import (
    simple_contact_array,
    staggered_contact_array,
    cluster_contact_array
)
from array_generator.exporters import (
    export_polygon_vertices,
    export_polygon_centroids,
    export_to_gds,
    export_array_metadata
)
from array_generator.visualizers import (
    plot_unit_cell,
    plot_array,
    save_unit_cell_plot,
    save_array_plot
)

__all__ = [
    # Core
    'Polygon',
    'UnitCell',
    'Array',
    # Constructors
    'rectangle_centered',
    'rectangle_corner',
    # Templates
    'simple_contact_array',
    'staggered_contact_array',
    'cluster_contact_array',
    # Exporters
    'export_polygon_vertices',
    'export_polygon_centroids',
    'export_to_gds',
    'export_array_metadata',
    # Visualizers
    'plot_unit_cell',
    'plot_array',
    'save_unit_cell_plot',
    'save_array_plot',
]
